version: '3.8'

services:
  risk-pipeline:
    build: .
    container_name: risk-pipeline
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs
      - ./notebooks:/app/notebooks
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8888:8888"  # For Jupyter
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root

  # Alternative: Run as CLI
  risk-pipeline-cli:
    build: .
    container_name: risk-pipeline-cli
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs
    environment:
      - PYTHONUNBUFFERED=1
    command: python -m risk_pipeline.cli
    profiles:
      - cli