[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "risk-model-pipeline"
version = "0.2.0"
description = "Production-ready risk modelling pipeline with dual approach: WOE transformation and raw variables"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [{ name = "Selim Oksuz", email = "selim.oksuz@example.com" }]
keywords = ["risk-modeling", "credit-risk", "machine-learning", "woe", "psi", "feature-selection"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Financial and Insurance Industry",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Office/Business :: Financial",
]
dependencies = [
    "pandas>=2.2",
    "numpy>=1.26",
    "scikit-learn>=1.4",
    "xgboost>=2.0",
    "lightgbm>=4.3",
    "matplotlib>=3.8",
    "shap>=0.45",
    "typer>=0.12",
    "pydantic>=2.7",
    "pyyaml>=6.0",
    "psutil>=5.9",
    "XlsxWriter>=3.2",
    "openpyxl>=3.1",
    "boruta>=0.3",
    "pygam>=0.10",
    "joblib>=1.3",
    "optuna>=3.6",
]

[project.scripts]
risk-pipeline = "risk_pipeline.cli:app"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
pythonpath = ["src"]

[project.optional-dependencies]
dev = [
  "pytest>=7",
  "black>=24",
  "flake8>=7",
  "isort>=5",
  "mypy>=1.8",
  "pre-commit>=3.5",
]

[project.urls]
Homepage = "https://github.com/selimoksuz/risk-model-pipeline"
Repository = "https://github.com/selimoksuz/risk-model-pipeline.git"
