[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "risk-model-pipeline"
version = "0.1.0"
description = "Modular risk modelling pipeline: WOE→PSI→FS→Model→Calibration→Report"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [{ name = "Your Name" }]
dependencies = [
    "pandas>=2.2",
    "numpy>=1.26",
    "scikit-learn>=1.4",
    "xgboost>=2.0",
    "lightgbm>=4.3",
    "matplotlib>=3.8",
    "shap>=0.45",
    "typer>=0.12",
    "pydantic>=2.7",
    "pyyaml>=6.0",
    "psutil>=5.9",
    "XlsxWriter>=3.2",
    "openpyxl>=3.1",
]

[project.scripts]
risk-pipeline = "risk_pipeline.cli:app"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
pythonpath = ["src"]
