name: CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -e .
      
      - name: Run flake8 linting
        run: |
          flake8 src tests --exit-zero --max-line-length=120
      
      - name: Run tests
        run: |
          pytest tests/ -v --tb=short || true